### PR TITLE
Tap 3839 7603 partition for pg as Source

### PR DESCRIPTION
**Pull request by 11000100111010101100111**

### CODE REVIEW

**Comment by dreamcoin1998** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.33557046979865773**
- Status: **ERROR**, MetricKey: **new_security_hotspots_reviewed**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3839-7603-partition-for-pg-source&id=tapdata-connectors

**Comment by dreamcoin1998** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.33557046979865773**
- Status: **ERROR**, MetricKey: **new_security_hotspots_reviewed**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3839-7603-partition-for-pg-source&id=tapdata-connectors

**Comment by dreamcoin1998** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.33557046979865773**
- Status: **ERROR**, MetricKey: **new_security_hotspots_reviewed**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3839-7603-partition-for-pg-source&id=tapdata-connectors

**Comment by dreamcoin1998** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **0.33557046979865773**
- Status: **ERROR**, MetricKey: **new_security_hotspots_reviewed**, ActualValue: **0.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3839-7603-partition-for-pg-source&id=tapdata-connectors

**Comment by dreamcoin1998** [comment]
SonarQube Quality Gate Status: **ERROR**

- Status: **ERROR**, MetricKey: **new_coverage**, ActualValue: **60.0**


See Sonar Scan Result at: http://58.251.34.123:29000/dashboard?branch=TAP-3839-7603-partition-for-pg-source&id=tapdata-connectors

**Review by jarad0628 — APPROVED** [review]

**Pull request merged**
